name: Node.js CI

on: [push]

jobs:
  node-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ['12', '14', '16']

    env:
      CI: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: npm install
        run: npm ci

      - name: Build the client library
        run: npm run build

      - name: Run tests
        run: npm run test:node

  browser-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    env:
      CI: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browser
        run: npx playwright install-deps ${{ matrix.browser }}

      - name: Build the client library
        run: npm run build

      - name: Run tests
        run: npm run test:browser
        env:
          BROWSER: ${{ matrix.browser }}
